version: '3'
services:
  postgres:
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin123"
      POSTGRES_DB: "lucasfs_objective_db"
    ports:
      - "5432:5432"
    networks:
      - lucasfs-compose-network

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "5050:80"
    networks:
      - lucasfs-compose-network

  app:
    build:
      context: ../../../
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: lucasfs-objective-app
    environment:
        QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres/lucasfs_objective_db
    ports:
      - "8080:8080"
    networks:
      - lucasfs-compose-network
    depends_on:
      - postgres

networks:
  lucasfs-compose-network:
    driver: bridge