version: '3'
services:
  postgres:
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin123"
      POSTGRES_DB: "lucasfs_objective_db"
    ports:
      - "5432:5432"
    networks:
      - lucasfs-compose-network

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "5050:80"
    networks:
      - lucasfs-compose-network

networks:
  lucasfs-compose-network:
    driver: bridge